# Generated by Django 3.2.4 on 2021-09-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_rf_classifier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bayesrfclassifier',
            name='accuracy',
        ),
        migrations.AddField(
            model_name='bayesrfclassifier',
            name='auc',
            field=models.TextField(blank=True),
        ),
    ]
