# Generated by Django 3.2.4 on 2021-09-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_rf_classifier', '0002_auto_20210919_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='bayesrfclassifier',
            name='feature_importance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bayesrfclassifier',
            name='hyper_parameters',
            field=models.TextField(blank=True),
        ),
    ]
