# Generated by Django 3.2.4 on 2021-09-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo_rf_regressor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bayesrfregressor',
            old_name='mae',
            new_name='error_measure',
        ),
    ]
