# Generated by Django 3.2.4 on 2021-08-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_donation', '0002_auto_20210820_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('payment_button_url', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Method',
        ),
    ]
