# Generated by Django 3.2.4 on 2021-09-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_time_series', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='is_score',
            new_name='is_label',
        ),
    ]
