# Generated by Django 3.2.4 on 2021-07-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='model_id',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='step',
            name='view_link',
            field=models.TextField(),
        ),
    ]
