# Generated by Django 4.0.4 on 2022-04-24 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0003_alter_paper_name'),
        ('task_manager', '0004_auto_20210916_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='predicted_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predicted_data', to='library.paper'),
        ),
    ]
