# Generated by Django 3.2.3 on 2021-06-22 02:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('subscription_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(decimal_places=2, max_digits=100)])),
                ('feature_items', models.TextField(blank=True)),
                ('badge', models.CharField(blank=True, max_length=16)),
                ('on_sale', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired_time', models.DateField(default=django.utils.timezone.now)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Redeem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('released_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('used_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.plan')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('coin', models.CharField(default='CNY', max_length=4)),
                ('plans', models.ManyToManyField(blank=True, to='payment.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contained_by', models.ManyToManyField(blank=True, to='payment.Plan')),
                ('product_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.productline')),
            ],
        ),
    ]
