# Generated by Django 3.2.4 on 2021-08-20 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.FloatField()),
                ('duration', models.IntegerField(verbose_name='subscription days')),
                ('promotion', models.CharField(blank=True, max_length=64, verbose_name='promotion slogan')),
                ('features', models.TextField(blank=True, help_text='one line each feature')),
                ('on_sale', models.BooleanField()),
                ('groups', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='permitted groups')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('paid', models.BooleanField()),
                ('method', models.CharField(blank=True, max_length=64)),
                ('token', models.CharField(blank=True, max_length=16)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_created_user', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired_time', models.DateTimeField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payment.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
