# Generated by Django 3.2.4 on 2021-06-23 14:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productline',
            name='plans',
        ),
        migrations.AddField(
            model_name='plan',
            name='permitted_groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='plan',
            name='product_line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payment.productline'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redeem',
            name='money_saved',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='subscription_days',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='redeem',
            name='released_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='redeem',
            name='used_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expired_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
