# Generated by Django 3.2.4 on 2021-06-23 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210623_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('trade_number', models.CharField(max_length=64)),
                ('returned_page', models.TextField()),
                ('paid', models.BooleanField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payment.plan')),
            ],
        ),
    ]
