# Generated by Django 3.2.4 on 2021-06-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('payment', '0005_auto_20210623_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='permitted_groups',
        ),
        migrations.AddField(
            model_name='plan',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.Permission'),
        ),
    ]
