# Generated by Django 3.2.4 on 2021-07-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('x_column', models.BooleanField(default=False)),
                ('y_column', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LinearRegression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
    ]
