# Generated by Django 3.2.4 on 2021-07-12 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_manager', '0001_initial'),
        ('algo_linear_regression', '0001_initial'),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linearregression',
            name='dataframe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_dataframe', to='library.paper'),
        ),
        migrations.AddField(
            model_name='linearregression',
            name='evaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_evaluation', to='library.paper'),
        ),
        migrations.AddField(
            model_name='linearregression',
            name='matrix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_matrix', to='library.paper'),
        ),
        migrations.AddField(
            model_name='linearregression',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_model', to='library.paper'),
        ),
        migrations.AddField(
            model_name='linearregression',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_manager.step'),
        ),
        migrations.AddField(
            model_name='column',
            name='linear_regression',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algo_linear_regression.linearregression'),
        ),
    ]
