# Generated by Django 3.2.4 on 2021-07-14 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('algo_linear_regression', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linearregression',
            name='evaluation',
        ),
        migrations.AddField(
            model_name='linearregression',
            name='evaluate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_evaluate', to='library.paper'),
        ),
        migrations.AddField(
            model_name='linearregression',
            name='predict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_predict', to='library.paper'),
        ),
    ]
