# Generated by Django 3.2.4 on 2021-07-14 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('algo_linear_regression', '0003_auto_20210714_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linearregression',
            name='dataframe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lr_dataframe', to='library.paper'),
        ),
        migrations.AlterField(
            model_name='linearregression',
            name='evaluate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lr_evaluate', to='library.paper'),
        ),
        migrations.AlterField(
            model_name='linearregression',
            name='matrix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lr_matrix', to='library.paper'),
        ),
        migrations.AlterField(
            model_name='linearregression',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lr_model', to='library.paper'),
        ),
        migrations.AlterField(
            model_name='linearregression',
            name='predict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lr_predict', to='library.paper'),
        ),
    ]
