# Generated by Django 3.2.4 on 2021-07-20 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo_linear_regression', '0004_auto_20210714_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='linear_regression',
            new_name='algorithm',
        ),
    ]
