# Generated by Django 3.2.4 on 2021-07-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_linear_regression', '0006_alter_linearregression_matrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='linearregression',
            name='coefficients',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linearregression',
            name='coefficients_deviate',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linearregression',
            name='mode',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='linearregression',
            name='regression_errors',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linearregression',
            name='significance',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
