# Generated by Django 3.2.4 on 2021-07-24 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0003_alter_paper_name'),
        ('algo_linear_regression', '0008_remove_linearregression_evaluate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linearregression',
            name='coefficients',
        ),
        migrations.RemoveField(
            model_name='linearregression',
            name='coefficients_deviate',
        ),
        migrations.RemoveField(
            model_name='linearregression',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='linearregression',
            name='regression_errors',
        ),
        migrations.RemoveField(
            model_name='linearregression',
            name='significance',
        ),
        migrations.AddField(
            model_name='linearregression',
            name='evaluate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lr_evaluate', to='library.paper'),
        ),
        migrations.AlterField(
            model_name='linearregression',
            name='matrix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lr_matrix', to='library.paper'),
        ),
    ]
