# Generated by Django 3.2.4 on 2021-07-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_descriptive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='y_column',
        ),
    ]
