# Generated by Django 3.2.9 on 2021-11-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_one_class_svm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bayesoneclasssvm',
            name='auc',
        ),
        migrations.RemoveField(
            model_name='bayesoneclasssvm',
            name='roc_curve',
        ),
        migrations.RemoveField(
            model_name='bayesoneclasssvm',
            name='training_history',
        ),
        migrations.AddField(
            model_name='bayesoneclasssvm',
            name='confusion_matrix',
            field=models.TextField(blank=True),
        ),
    ]
