# Generated by Django 3.2.9 on 2021-11-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo_svm_classifier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bayessvmclassifier',
            name='feature_importance',
        ),
    ]
