# Generated by Django 3.2.9 on 2021-11-18 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_manager', '0004_auto_20210916_1126'),
        ('library', '0003_alter_paper_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BayesLogisticRegression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, choices=[('5_fold', '5 fold cross validation'), ('split', 'Random split to 80% training set, 20% validation set'), ('full_train', 'Applying all samples for training')], max_length=10)),
                ('hyper_parameters', models.TextField(blank=True)),
                ('class_dict', models.TextField(blank=True)),
                ('training_history', models.TextField(blank=True)),
                ('auc', models.TextField(blank=True)),
                ('roc_curve', models.TextField(blank=True)),
                ('dataframe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lgr_dataframe', to='library.paper')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lgr_model', to='library.paper')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_manager.step')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('x_column', models.BooleanField(default=False)),
                ('y_column', models.BooleanField(default=False)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algo_logistic_regression.bayeslogisticregression')),
            ],
        ),
    ]
