# Generated by Django 4.0 on 2021-12-25 02:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('badge', models.CharField(blank=True, max_length=16)),
                ('duration', models.IntegerField(help_text='Unit: days')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(help_text='ISO 4217 currency code.', max_length=4)),
                ('description', models.TextField(blank=True)),
                ('on_sale', models.BooleanField(default=True)),
                ('permitted_groups', models.ManyToManyField(blank=True, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(max_length=4)),
                ('token', models.CharField(max_length=32)),
                ('paid', models.BooleanField()),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_paypal', to='auth.user')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='paypal.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired_time', models.DateTimeField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='paypal.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='LockedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
    ]
