# Generated by Django 3.2.7 on 2021-09-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('paypal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='permitted_groups',
        ),
        migrations.AddField(
            model_name='plan',
            name='permitted_groups',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Group'),
        ),
    ]
