# Generated by Django 3.2.7 on 2021-09-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0002_auto_20210907_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.IntegerField(help_text='Unit: days'),
        ),
    ]
