# Generated by Django 3.2.7 on 2021-09-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('paypal', '0003_alter_plan_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='token',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='permitted_groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
