# Generated by Django 3.2.4 on 2021-09-19 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0003_alter_paper_name'),
        ('pre_norm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalization',
            name='transformed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='norm_transformed', to='library.paper'),
        ),
        migrations.AlterField(
            model_name='normalization',
            name='dataframe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='norm_dataframe', to='library.paper'),
        ),
    ]
