# Generated by Django 3.2.4 on 2021-08-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0003_alter_paper_name'),
        ('pre_norm', '0002_auto_20210805_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalization',
            name='mapper',
            field=models.ManyToManyField(blank=True, related_name='normalization_mapping', to='library.Paper'),
        ),
        migrations.DeleteModel(
            name='Mapping',
        ),
    ]
