# Generated by Django 3.2.4 on 2021-08-05 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0003_alter_paper_name'),
        ('pre_norm', '0003_auto_20210805_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normalization',
            name='mapper',
        ),
        migrations.AddField(
            model_name='normalization',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalization_mapping', to='library.paper'),
        ),
    ]
