# Generated by Django 3.2.4 on 2021-08-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_norm', '0004_auto_20210805_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='x',
            field=models.BooleanField(default=False),
        ),
    ]
