# Generated by Django 3.2.4 on 2021-08-05 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0003_alter_paper_name'),
        ('pre_norm', '0005_column_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalization',
            name='predict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='norm_predict', to='library.paper'),
        ),
        migrations.AlterField(
            model_name='normalization',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='norm_model', to='library.paper'),
        ),
    ]
