# Generated by Django 3.2.9 on 2021-11-20 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_manager', '0004_auto_20210916_1126'),
        ('library', '0003_alter_paper_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDBSCAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knn_figure', models.TextField(blank=True)),
                ('class_dict', models.TextField(blank=True)),
                ('dataframe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbscan_dataframe', to='library.paper')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbscan_model', to='library.paper')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_manager.step')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('x_column', models.BooleanField(default=False)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algo_dbscan.mydbscan')),
            ],
        ),
    ]
