# Generated by Django 3.2.4 on 2021-09-19 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_manager', '0004_auto_20210916_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(blank=True)),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_manager.step')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pre_cross_sectional.preprocessing')),
            ],
        ),
    ]
