# Generated by Django 3.2.4 on 2021-07-19 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_cross_sectional', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='pre_processing',
            new_name='preprocessing',
        ),
    ]
