# Generated by Django 3.2.4 on 2021-07-19 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_cross_sectional', '0002_rename_pre_processing_column_preprocessing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='x_column',
        ),
    ]
