# Generated by Django 3.2.4 on 2021-07-20 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_cross_sectional', '0003_remove_column_x_column'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='preprocessing',
            new_name='algorithm',
        ),
    ]
